import {
  dynamicEntries,
  dynamicTypes,
  iconExports,
  iconImports,
  iconNameType,
  iconNode,
  iconRegistryEntries,
  iconRegistryTypes,
  prepareDist,
  write,
} from "./shared.mjs";

export async function buildPreactPackage(icons, dist) {
  await prepareDist(dist);
  await write(dist, "types.d.ts", `import type { ComponentType, JSX } from "preact";\nexport type SVGElementType = "circle" | "ellipse" | "line" | "path" | "polygon" | "polyline" | "rect";\nexport type IconNode = readonly [tag: SVGElementType, attrs: Record<string, string>][];\nexport interface VadivamProps extends Omit<JSX.SVGAttributes<SVGSVGElement>, "color" | "size"> { name?: string; size?: string | number; color?: string; strokeWidth?: string | number; absoluteStrokeWidth?: boolean; title?: string; iconNode?: IconNode; }\nexport type VadivamIcon = ComponentType<VadivamProps>;\nexport type IconName = ${iconNameType(icons)};\n`);
  await write(dist, "defaultAttributes.js", `export default { xmlns: "http://www.w3.org/2000/svg", width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": 2, "stroke-linecap": "round", "stroke-linejoin": "round" };\n`);
  await write(dist, "context.js", `import { createContext, h } from "preact";\nimport { useContext, useMemo } from "preact/hooks";\nexport const VadivamContext = createContext({});\nexport function VadivamProvider({ children, size, color, strokeWidth, absoluteStrokeWidth, class: className }) { const value = useMemo(() => ({ size, color, strokeWidth, absoluteStrokeWidth, class: className }), [size, color, strokeWidth, absoluteStrokeWidth, className]); return h(VadivamContext.Provider, { value }, children); }\nexport function useVadivamContext() { return useContext(VadivamContext); }\n`);
  await write(dist, "context.d.ts", `import type { ComponentChildren } from "preact";\nimport type { VadivamProps } from "./types.js";\nexport interface VadivamProviderProps extends Pick<VadivamProps, "size" | "color" | "strokeWidth" | "absoluteStrokeWidth" | "class"> { children: ComponentChildren; }\nexport declare function VadivamProvider(props: VadivamProviderProps): import("preact").VNode;\nexport declare function useVadivamContext(): Partial<VadivamProps>;\n`);
  await write(dist, "Icon.js", `import { h, toChildArray } from "preact";\nimport defaultAttributes from "./defaultAttributes.js";\nimport { useVadivamContext } from "./context.js";\nfunction classes(...values) { return values.flatMap((value) => typeof value === "string" ? value.split(/\\s+/) : []).filter((value, index, all) => value && all.indexOf(value) === index).join(" "); }\nfunction hasA11y(props) { return Object.keys(props).some((name) => name.startsWith("aria-") || name === "role" || name === "title"); }\nexport function Icon({ color, size, strokeWidth, absoluteStrokeWidth, children, iconNode = [], name, title, class: className = "", className: reactClass = "", ...rest }) { const context = useVadivamContext() ?? {}; const resolvedSize = size ?? context.size ?? 24; const resolvedStroke = strokeWidth ?? context.strokeWidth ?? 2; const numericSize = Number(resolvedSize); const numericStroke = Number(resolvedStroke); const absolute = absoluteStrokeWidth ?? context.absoluteStrokeWidth ?? false; const calculated = absolute && Number.isFinite(numericSize) && numericSize !== 0 && Number.isFinite(numericStroke) ? numericStroke * 24 / numericSize : resolvedStroke; const labelled = Boolean(title) || hasA11y(rest); return h("svg", { ...defaultAttributes, width: resolvedSize, height: resolvedSize, stroke: color ?? context.color ?? "currentColor", "stroke-width": calculated, class: classes("vadivam", name && "vadivam-" + name, context.class, className, reactClass), ...(!labelled ? { "aria-hidden": "true" } : {}), ...(title ? { role: "img" } : {}), ...rest }, [title ? h("title", null, title) : null, ...iconNode.map(([tag, attrs]) => h(tag, attrs)), ...toChildArray(children)]); }\nexport default Icon;\n`);
  await write(dist, "Icon.d.ts", `import type { VadivamProps } from "./types.js";\nexport declare function Icon(props: VadivamProps): import("preact").VNode;\nexport default Icon;\n`);
  await write(dist, "createVadivamIcon.js", `import { h } from "preact";\nimport Icon from "./Icon.js";\nexport function createVadivamIcon(iconName, iconNode) { const Component = ({ children, ...props }) => h(Icon, { ...props, name: iconName, iconNode }, children); Component.displayName = iconName.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(""); return Component; }\nexport default createVadivamIcon;\n`);
  await write(dist, "createVadivamIcon.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport declare function createVadivamIcon(iconName: string, iconNode: IconNode): VadivamIcon;\nexport default createVadivamIcon;\n`);
  for (const icon of icons) {
    await write(dist, `icons/${icon.name}.js`, `import { createVadivamIcon } from "../createVadivamIcon.js";\nexport const __iconNode = ${iconNode(icon)};\nexport default createVadivamIcon("${icon.name}", __iconNode);\n`);
    await write(dist, `icons/${icon.name}.d.ts`, `import type { IconNode, VadivamIcon } from "../types.js";\nexport declare const __iconNode: IconNode;\ndeclare const icon: VadivamIcon;\nexport default icon;\n`);
  }
  await write(dist, "icons.js", `${iconImports(icons)}\nexport const icons = {\n${iconRegistryEntries(icons)}\n};\nexport default icons;\n`);
  await write(dist, "icons.d.ts", `import type { VadivamIcon } from "./types.js";\nexport declare const icons: {\n${iconRegistryTypes(icons, "VadivamIcon")}\n};\nexport default icons;\n`);
  await write(dist, "icons/index.js", `${iconExports(icons, "./")}\n`);
  await write(dist, "icons/index.d.ts", `${iconExports(icons, "./")}\n`);
  await write(dist, "dynamicIconImports.js", `const dynamicIconImports = {\n${dynamicEntries(icons)}\n};\nexport const iconNames = Object.keys(dynamicIconImports);\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamicIconImports.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport interface DynamicIconModule { default: VadivamIcon; __iconNode: IconNode; }\ndeclare const dynamicIconImports: {\n${dynamicTypes(icons)}\n};\nexport declare const iconNames: readonly (keyof typeof dynamicIconImports)[];\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamic.js", `import { h } from "preact";\nimport { useEffect, useRef, useState } from "preact/hooks";\nimport dynamicIconImports, { iconNames } from "./dynamicIconImports.js";\nexport function DynamicIcon({ name, fallback = null, ...props }) { const [Component, setComponent] = useState(null); const request = useRef(0); useEffect(() => { const id = ++request.current; setComponent(null); const importer = dynamicIconImports[name]; if (importer) importer().then((module) => { if (request.current === id) setComponent(() => module.default); }, () => { if (request.current === id) setComponent(null); }); return () => { request.current += 1; }; }, [name]); return Component ? h(Component, props) : fallback; }\nexport { dynamicIconImports, iconNames };\nexport default DynamicIcon;\n`);
  await write(dist, "dynamic.d.ts", `import type { ComponentChildren } from "preact";\nimport type { IconName, VadivamProps } from "./types.js";\nexport interface DynamicIconProps extends VadivamProps { name: IconName; fallback?: ComponentChildren; }\nexport declare function DynamicIcon(props: DynamicIconProps): import("preact").ComponentChildren;\nexport { default as dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport default DynamicIcon;\n`);
  const exports = iconExports(icons);
  await write(dist, "index.js", `${exports}\nexport { Icon } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { icons } from "./icons.js";\nexport { VadivamContext, VadivamProvider, useVadivamContext } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\n`);
  await write(dist, "index.d.ts", `${exports}\nexport { Icon } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { icons } from "./icons.js";\nexport { VadivamProvider, useVadivamContext } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport type { IconName, IconNode, SVGElementType, VadivamIcon, VadivamProps } from "./types.js";\n`);
}
