import {
  dynamicEntries,
  dynamicTypes,
  iconExports,
  iconNameType,
  prepareDist,
  write,
} from "./shared.mjs";

export async function buildReactNativePackage(icons, dist) {
  await prepareDist(dist);
  const names = iconNameType(icons);
  await write(dist, "types.d.ts", `import type * as React from "react";\nimport type { Svg, SvgProps } from "react-native-svg";\nexport type SVGElementType = "circle" | "ellipse" | "line" | "path" | "polygon" | "polyline" | "rect";\nexport type IconNode = readonly [tag: SVGElementType, attrs: Record<string, string>][];\nexport interface VadivamProps extends SvgProps { size?: string | number; absoluteStrokeWidth?: boolean; title?: string; "data-testid"?: string; }\nexport type VadivamIcon = React.ForwardRefExoticComponent<VadivamProps & React.RefAttributes<Svg>>;\nexport type IconName = ${names};\n`);
  await write(dist, "defaultAttributes.js", `const defaultAttributes = { xmlns: "http://www.w3.org/2000/svg", width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, strokeLinecap: "round", strokeLinejoin: "round" };\nexport const childDefaultAttributes = { fill: defaultAttributes.fill, stroke: defaultAttributes.stroke, strokeWidth: defaultAttributes.strokeWidth, strokeLinecap: defaultAttributes.strokeLinecap, strokeLinejoin: defaultAttributes.strokeLinejoin };\nexport default defaultAttributes;\n`);
  await write(dist, "context.js", `import React from "react";\nconst VadivamContext = React.createContext({});\nexport function VadivamProvider({ children, size, color, strokeWidth, absoluteStrokeWidth }) {\n  const value = React.useMemo(() => ({ size, color, strokeWidth, absoluteStrokeWidth }), [size, color, strokeWidth, absoluteStrokeWidth]);\n  return React.createElement(VadivamContext.Provider, { value }, children);\n}\nexport function useVadivamContext() { return React.useContext(VadivamContext); }\n`);
  await write(dist, "context.d.ts", `import type * as React from "react";\nimport type { VadivamProps } from "./types.js";\nexport interface VadivamProviderProps extends Pick<VadivamProps, "size" | "color" | "strokeWidth" | "absoluteStrokeWidth"> { children: React.ReactNode; }\nexport declare function VadivamProvider(props: VadivamProviderProps): React.ReactElement;\nexport declare function useVadivamContext(): Partial<VadivamProps>;\n`);
  await write(dist, "Icon.js", `import React, { forwardRef } from "react";\nimport * as NativeSvg from "react-native-svg";\nimport defaultAttributes, { childDefaultAttributes } from "./defaultAttributes.js";\nimport { useVadivamContext } from "./context.js";\nconst primitives = { circle: NativeSvg.Circle, ellipse: NativeSvg.Ellipse, line: NativeSvg.Line, path: NativeSvg.Path, polygon: NativeSvg.Polygon, polyline: NativeSvg.Polyline, rect: NativeSvg.Rect };\nfunction renderNode([tag, attrs], customAttrs) { return React.createElement(primitives[tag], { ...childDefaultAttributes, ...customAttrs, ...attrs }); }\nexport const Icon = forwardRef(({ color, size, strokeWidth, absoluteStrokeWidth, children, iconNode, title, className, testID, ...rest }, ref) => {\n  const context = useVadivamContext() ?? {};\n  const resolvedSize = size ?? context.size ?? 24;\n  const resolvedStrokeWidth = strokeWidth ?? context.strokeWidth ?? 2;\n  const numericSize = Number(resolvedSize);\n  const numericStrokeWidth = Number(resolvedStrokeWidth);\n  const absolute = absoluteStrokeWidth ?? context.absoluteStrokeWidth ?? false;\n  const calculated = absolute && Number.isFinite(numericSize) && numericSize !== 0 && Number.isFinite(numericStrokeWidth) ? numericStrokeWidth * 24 / numericSize : resolvedStrokeWidth;\n  const customAttrs = { stroke: color ?? context.color ?? "currentColor", strokeWidth: calculated, ...rest };\n  return React.createElement(NativeSvg.Svg, { ref, ...defaultAttributes, width: resolvedSize, height: resolvedSize, testID, "data-testid": testID, className, accessibilityRole: title ? "image" : rest.accessibilityRole, ...customAttrs }, ...iconNode.map((node) => renderNode(node, customAttrs)), title ? React.createElement(NativeSvg.Title, null, title) : null, ...React.Children.toArray(children));\n});\nIcon.displayName = "Icon";\nexport default Icon;\n`);
  await write(dist, "Icon.d.ts", `import type * as React from "react";\nimport type { Svg } from "react-native-svg";\nimport type { IconNode, VadivamProps } from "./types.js";\nexport interface IconProps extends VadivamProps { iconNode: IconNode; }\nexport declare const Icon: React.ForwardRefExoticComponent<IconProps & React.RefAttributes<Svg>>;\nexport default Icon;\n`);
  await write(dist, "createVadivamIcon.js", `import React, { forwardRef } from "react";\nimport Icon from "./Icon.js";\nexport function createVadivamIcon(iconName, iconNode) { const Component = forwardRef((props, ref) => React.createElement(Icon, { ref, iconNode, ...props })); Component.displayName = iconName.split(/[-_ ]+/).filter(Boolean).map((part) => part[0].toUpperCase() + part.slice(1)).join(""); return Component; }\nexport default createVadivamIcon;\n`);
  await write(dist, "createVadivamIcon.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport declare function createVadivamIcon(iconName: string, iconNode: IconNode): VadivamIcon;\nexport default createVadivamIcon;\n`);
  for (const icon of icons) {
    await write(dist, `icons/${icon.name}.js`, `import { createVadivamIcon } from "../createVadivamIcon.js";\nexport const __iconNode = ${JSON.stringify(icon.iconNode)};\nconst ${icon.componentName} = createVadivamIcon("${icon.name}", __iconNode);\nexport default ${icon.componentName};\n`);
    await write(dist, `icons/${icon.name}.d.ts`, `import type { IconNode, VadivamIcon } from "../types.js";\nexport declare const __iconNode: IconNode;\ndeclare const ${icon.componentName}: VadivamIcon;\nexport default ${icon.componentName};\n`);
  }
  const exports = iconExports(icons);
  await write(dist, "icons/index.js", `${iconExports(icons, "./")}\n`);
  await write(dist, "icons/index.d.ts", `${iconExports(icons, "./")}\n`);
  await write(dist, "dynamicIconImports.js", `const dynamicIconImports = {\n${dynamicEntries(icons)}\n};\nexport const iconNames = Object.keys(dynamicIconImports);\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamicIconImports.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport interface DynamicIconModule { default: VadivamIcon; __iconNode: IconNode; }\ndeclare const dynamicIconImports: {\n${dynamicTypes(icons)}\n};\nexport declare const iconNames: readonly (keyof typeof dynamicIconImports)[];\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamic.js", `import React, { forwardRef } from "react";\nimport dynamicIconImports, { iconNames } from "./dynamicIconImports.js";\nexport const DynamicIcon = forwardRef(({ name, fallback = null, ...props }, ref) => { const importer = dynamicIconImports[name]; const Component = React.useMemo(() => importer ? React.lazy(importer) : null, [importer]); if (!Component) return fallback; return React.createElement(React.Suspense, { fallback }, React.createElement(Component, { ...props, ref })); });\nDynamicIcon.displayName = "DynamicIcon";\nexport { dynamicIconImports, iconNames };\nexport default DynamicIcon;\n`);
  await write(dist, "dynamic.d.ts", `import type * as React from "react";\nimport type { Svg } from "react-native-svg";\nimport type { IconName, VadivamProps } from "./types.js";\nexport interface DynamicIconProps extends VadivamProps { name: IconName; fallback?: React.ReactNode; }\nexport declare const DynamicIcon: React.ForwardRefExoticComponent<DynamicIconProps & React.RefAttributes<Svg>>;\nexport { default as dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport default DynamicIcon;\n`);
  await write(dist, "index.js", `${exports}\nexport { Icon } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { VadivamProvider, useVadivamContext } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\n`);
  await write(dist, "index.d.ts", `${exports}\nexport { Icon } from "./Icon.js";\nexport type { IconProps } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { VadivamProvider, useVadivamContext } from "./context.js";\nexport type { VadivamProviderProps } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport type { IconName, IconNode, SVGElementType, VadivamIcon, VadivamProps } from "./types.js";\n`);
}
