import {
  dynamicEntries,
  dynamicTypes,
  iconExports,
  iconImports,
  iconNameType,
  iconNode,
  iconRegistryEntries,
  iconRegistryTypes,
  prepareDist,
  write,
} from "./shared.mjs";

export async function buildVuePackage(icons, dist) {
  await prepareDist(dist);
  await write(dist, "types.d.ts", `import type { FunctionalComponent, SVGAttributes } from "vue";\nexport type SVGElementType = "circle" | "ellipse" | "line" | "path" | "polygon" | "polyline" | "rect";\nexport type IconNode = readonly [tag: SVGElementType, attrs: Record<string, string>][];\nexport interface VadivamProps extends Partial<SVGAttributes> { name?: string; size?: string | number; color?: string; strokeWidth?: string | number; absoluteStrokeWidth?: boolean; title?: string; iconNode?: IconNode; }\nexport type VadivamIcon = FunctionalComponent<VadivamProps>;\nexport type IconName = ${iconNameType(icons)};\n`);
  await write(dist, "defaultAttributes.js", `export default { xmlns: "http://www.w3.org/2000/svg", width: 24, height: 24, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", "stroke-width": 2, "stroke-linecap": "round", "stroke-linejoin": "round" };\n`);
  await write(dist, "context.js", `import { defineComponent, h, inject, provide } from "vue";\nexport const VADIVAM_CONTEXT = Symbol("vadivam-icons");\nexport function provideVadivam(props) { provide(VADIVAM_CONTEXT, props); return props; }\nexport function useVadivamContext() { return inject(VADIVAM_CONTEXT, {}); }\nexport const VadivamProvider = defineComponent({ name: "VadivamProvider", inheritAttrs: false, props: { size: [String, Number], color: String, strokeWidth: [String, Number], absoluteStrokeWidth: Boolean, class: String }, setup(props, { slots }) { provideVadivam(props); return () => slots.default?.() ?? null; } });\n`);
  await write(dist, "context.d.ts", `import type { DefineComponent } from "vue";\nimport type { VadivamProps } from "./types.js";\nexport declare const VADIVAM_CONTEXT: unique symbol;\nexport declare function provideVadivam(props: Partial<VadivamProps>): Partial<VadivamProps>;\nexport declare function useVadivamContext(): Partial<VadivamProps>;\nexport declare const VadivamProvider: DefineComponent<Pick<VadivamProps, "size" | "color" | "strokeWidth" | "absoluteStrokeWidth" | "class">>;\n`);
  await write(dist, "Icon.js", `import { h } from "vue";\nimport defaultAttributes from "./defaultAttributes.js";\nimport { useVadivamContext } from "./context.js";\nfunction classes(...values) { return values.flatMap((value) => typeof value === "string" ? value.split(/\\s+/) : []).filter((value, index, all) => value && all.indexOf(value) === index).join(" "); }\nfunction hasA11y(attrs) { return Object.keys(attrs).some((name) => name.startsWith("aria-") || name === "role" || name === "title"); }\nexport function Icon(props, { attrs, slots }) { const context = useVadivamContext(); const size = props.size ?? context.size ?? 24; const strokeWidth = props.strokeWidth ?? context.strokeWidth ?? 2; const numericSize = Number(size); const numericStroke = Number(strokeWidth); const absolute = props.absoluteStrokeWidth ?? context.absoluteStrokeWidth ?? false; const calculated = absolute && Number.isFinite(numericSize) && numericSize !== 0 && Number.isFinite(numericStroke) ? numericStroke * 24 / numericSize : strokeWidth; const labelled = Boolean(props.title) || hasA11y(attrs); return h("svg", { ...defaultAttributes, ...attrs, width: size, height: size, stroke: props.color ?? context.color ?? "currentColor", "stroke-width": calculated, class: classes("vadivam", props.name && "vadivam-" + props.name, context.class, attrs.class), ...(!labelled ? { "aria-hidden": "true" } : {}), ...(props.title ? { role: "img" } : {}) }, [props.title ? h("title", props.title) : null, ...(props.iconNode ?? []).map(([tag, nodeAttrs]) => h(tag, nodeAttrs)), ...(slots.default?.() ?? [])]); }\nIcon.props = ["name", "iconNode", "size", "color", "strokeWidth", "absoluteStrokeWidth", "title"];\nIcon.inheritAttrs = false;\nIcon.displayName = "Icon";\nexport default Icon;\n`);
  await write(dist, "Icon.d.ts", `import type { VadivamIcon } from "./types.js";\nexport declare const Icon: VadivamIcon;\nexport default Icon;\n`);
  await write(dist, "createVadivamIcon.js", `import { h } from "vue";\nimport Icon from "./Icon.js";\nexport function createVadivamIcon(iconName, iconNode) { const Component = (props, context) => h(Icon, { ...context.attrs, ...props, name: iconName, iconNode }, context.slots); Component.props = Icon.props; Component.inheritAttrs = false; Component.displayName = iconName.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(""); return Component; }\nexport default createVadivamIcon;\n`);
  await write(dist, "createVadivamIcon.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport declare function createVadivamIcon(iconName: string, iconNode: IconNode): VadivamIcon;\nexport default createVadivamIcon;\n`);
  for (const icon of icons) {
    await write(dist, `icons/${icon.name}.js`, `import { createVadivamIcon } from "../createVadivamIcon.js";\nexport const __iconNode = ${iconNode(icon)};\nexport default createVadivamIcon("${icon.name}", __iconNode);\n`);
    await write(dist, `icons/${icon.name}.d.ts`, `import type { IconNode, VadivamIcon } from "../types.js";\nexport declare const __iconNode: IconNode;\ndeclare const icon: VadivamIcon;\nexport default icon;\n`);
  }
  await write(dist, "icons.js", `${iconImports(icons)}\nexport const icons = {\n${iconRegistryEntries(icons)}\n};\nexport default icons;\n`);
  await write(dist, "icons.d.ts", `import type { VadivamIcon } from "./types.js";\nexport declare const icons: {\n${iconRegistryTypes(icons, "VadivamIcon")}\n};\nexport default icons;\n`);
  await write(dist, "icons/index.js", `${iconExports(icons, "./")}\n`);
  await write(dist, "icons/index.d.ts", `${iconExports(icons, "./")}\n`);
  await write(dist, "dynamicIconImports.js", `const dynamicIconImports = {\n${dynamicEntries(icons)}\n};\nexport const iconNames = Object.keys(dynamicIconImports);\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamicIconImports.d.ts", `import type { IconNode, VadivamIcon } from "./types.js";\nexport interface DynamicIconModule { default: VadivamIcon; __iconNode: IconNode; }\ndeclare const dynamicIconImports: {\n${dynamicTypes(icons)}\n};\nexport declare const iconNames: readonly (keyof typeof dynamicIconImports)[];\nexport { dynamicIconImports };\nexport default dynamicIconImports;\n`);
  await write(dist, "dynamic.js", `import { defineAsyncComponent, defineComponent, h } from "vue";\nimport dynamicIconImports, { iconNames } from "./dynamicIconImports.js";\nexport const DynamicIcon = defineComponent({ name: "DynamicIcon", inheritAttrs: false, props: { name: { type: String, required: true }, fallback: null }, setup(props, { attrs, slots }) { return () => { const importer = dynamicIconImports[props.name]; if (!importer) return slots.fallback?.() ?? props.fallback ?? null; const AsyncIcon = defineAsyncComponent({ loader: importer, loadingComponent: slots.fallback ? { setup: () => slots.fallback } : undefined }); return h(AsyncIcon, attrs, slots); }; } });\nexport { dynamicIconImports, iconNames };\nexport default DynamicIcon;\n`);
  await write(dist, "dynamic.d.ts", `import type { DefineComponent } from "vue";\nimport type { IconName, VadivamProps } from "./types.js";\nexport interface DynamicIconProps extends VadivamProps { name: IconName; fallback?: unknown; }\nexport declare const DynamicIcon: DefineComponent<DynamicIconProps>;\nexport { default as dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport default DynamicIcon;\n`);
  const exports = iconExports(icons);
  await write(dist, "index.js", `${exports}\nexport { Icon } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { icons } from "./icons.js";\nexport { VADIVAM_CONTEXT, VadivamProvider, provideVadivam, useVadivamContext } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\n`);
  await write(dist, "index.d.ts", `${exports}\nexport { Icon } from "./Icon.js";\nexport { createVadivamIcon } from "./createVadivamIcon.js";\nexport { icons } from "./icons.js";\nexport { VADIVAM_CONTEXT, VadivamProvider, provideVadivam, useVadivamContext } from "./context.js";\nexport { dynamicIconImports, iconNames } from "./dynamicIconImports.js";\nexport type { IconName, IconNode, SVGElementType, VadivamIcon, VadivamProps } from "./types.js";\n`);
}
